### ISSUE TITLE
An instance is already running

### ISSUE THREAD

**Issue by ANDREW007CZ** [jonaskohl/CapsLockIndicator#1]
I am having trouble when opening the utility. It always says: An instance is already running. But there is no instance running, it occured even when first opening. 
It works when I start it in Avast Sandbox only.

**Comment by jonaskohl** [comment]
I could not reproduce the problem. In my testing, CapsLock Indicator started without any problems inside the Avast Sandbox.

**Tested using the following configuration:**

    Windows 10 Pro 64-Bit
    Avast Pro Antivirus 17.8.2318 (build 17.8.3705.249)
    CapsLock Indicator 3.4.0.0

![17_12_2017_15_12_15](https://user-images.githubusercontent.com/23175424/34080390-3aa1399a-e33d-11e7-997b-af26d8ae5e2d.png)

**Comment by ANDREW007CZ** [comment]
Hey,
sorry, we misunderstood. I meant I cant start program normally. It says that there is an instance running already.
But when I open it in Avast Sandbox, it works, it can start.

**Comment by jonaskohl** [comment]
I will test this later

**Comment by jonaskohl** [comment]
Sorry for the late response. I sadly still could not reproduce the described behaviour. Make sure there are no processes named "CLIv3-3.4.0.0.exe" running.

**Comment by ANDREW007CZ** [comment]
Hello, the problem is gone. I can run it just fine. Thank you for making this hepler. :)
