### ISSUE TITLE
Allow localisation into other languages

### ISSUE THREAD

**Issue by adrmzz** [jonaskohl/CapsLockIndicator#10]
If I am not wrong, the software is only in English. Could you please establish a platform for localisation in order for the community to localise it into other languages?

**Comment by jonaskohl** [comment]
At some point, I'd like to. I still need to find a good, free platform for crowdsourced translations.

**Comment by jonaskohl** [comment]
Implemented in version 3.5.0.0. Visit [http://cli.jonaskohl.de/!/translations](http://cli.jonaskohl.de/!/translations) for more information.
