### ISSUE TITLE
Icon does not change (but notification appears)

### ISSUE THREAD

**Issue by snowleopard-1** [jonaskohl/CapsLockIndicator#101]
I recently bought an ASUS TUF.

I get the notification when num lock goes on or off. But shouldn't the icon also switch? I just see an "N" whenther num lock is on or off. I would also like the icon to be in the task bar itself and not among the "extra" icons accessible by the up arrow.

I checked the "show icons for ... num lock" box.

I don't use Windows so much and am new to this so I may have misunderstood.
Thank you for keeping up open software.

**Comment by Yetoo1** [comment]
@snowleopard-1 You can move the icons you want in the extra icon area to the taskbar by click and dragging it.

**Comment by snowleopard-1** [comment]
Thank you. Works fine. I should have known that.

But the first problem persists. I can only see an "N" as an icon, it does not change with pressing the num lock key on or off.

**Comment by jonaskohl** [comment]
Which version of Windows and CapsLock Indicator are you using? Are you using the default icon pack or have you installed an icon pack from the Icon Pack Gallery?

**Comment by snowleopard-1** [comment]
Windows 10.0.19041
CapsLock 3.15.0.0

I just installed it. I have not done any changes or downloads.

**Comment by jonaskohl** [comment]
Hmm, weird... I have never come across this bug before... I will investigate this. Is there any chance you could provide a screen recording of the CapsLock Indicator icon showing this behaviour?
