### ISSUE TITLE
Auto Update Still Not Working

### ISSUE THREAD

**Issue by DaveH1** [jonaskohl/CapsLockIndicator#102]
The automatic update system still fails for me.
It downloads fine, but when the "Restart" button is pressed, a .NET exception comes up.
I have to update manually all the time, and always have had to.

![Screenshot 5](https://user-images.githubusercontent.com/6755753/145617739-a4bbbeb0-0f12-4d85-bee5-cda9cc5a6a14.png)

Cheers, Dave.

**Comment by jonaskohl** [comment]
Which version are you updating from?

**Comment by DaveH1** [comment]
I can't remember now, but it would have been the previous version to the current one, as I have always installed every update that's been issued. This problem has been there for a long time, with every version. I always end up having to do the whole update manually. Cheers, Dave.

**Comment by jonaskohl** [comment]
Could you please post the details presented in the exception dialog?

**Comment by DaveH1** [comment]
I'm not sure how I can do that now until the next update.

**Comment by jonaskohl** [comment]
You can try downloading an older version, e.g. [3.14.0.0 here](https://clireleases.jonaskohl.de/releases/simple.php?css=true&only=3.14.0.0) and updating from that

**Comment by DaveH1** [comment]
Thanks, I'll give that a try.

**Comment by DaveH1** [comment]
Error #1 appears the first time I hit "restart".
Error # appears on subsequent attempts.
HTH. Cheers, Dave.

[Error1.txt](https://github.com/jonaskohl/CapsLockIndicator/files/7849790/Error1.txt)
[Error2.txt](https://github.com/jonaskohl/CapsLockIndicator/files/7849792/Error2.txt)
