### ISSUE TITLE
Keyboard layout indicator

### ISSUE THREAD

**Issue by oleg-sgh** [jonaskohl/CapsLockIndicator#103]
Hello.
Is it possible to add a keyboard layout indicator when enabling a layout other than the default one?

**Comment by jonaskohl** [comment]
Doesn't Windows already come with an input indicator?

**Comment by oleg-sgh** [comment]
> Doesn't Windows already come with an input indicator?

It is very small and not noticeable. It would be nice if there would be the same notification with a different layout. I use the on-screen notification mode when Num Lock, Caps Lock, and Scroll Lock are on.

**Comment by jonaskohl** [comment]
I have taken another look at it and implementing this seems to be a huge undertaking, as there is a) no managed function to retrieve the current keyboard layout, so p/invoking would be necessary and b) the keyboard layout is set on a per-thread basis, thus making it really difficult to retrieve the keyboard layout for any given process.

**Comment by oleg-sgh** [comment]
I now have a homemade app on AutoHotkey.
Maybe something will help.

Color1 := "0x0C0BC0", Color2 := "0x0FFC00", x := 1000, y := 500, w := 18, h := 18
loop
{   
   If (InputLayout() = "Russian")
   {   
      Gui, +AlwaysOnTop -Caption +ToolWindow +LastFound
      Gui, Color, % Color1
      Gui, Show, x%x% y%y% w%w% h%h% NA
   }
   Else If (InputLayout() = "English")
   {   
      Gui, +AlwaysOnTop -Caption +ToolWindow +LastFound
      Gui, Color, % Color2
      Gui, Show, x%x% y%y% w%w% h%h% NA
   }
   sleep, 50
}

InputLayout()
{
    ThreadID := DllCall("GetWindowThreadProcessId", "Int", WinExist("A"), "Int", 0)
    HKL := DllCall("GetKeyboardLayout", "uint", ThreadID, "UShort")
    VarSetCapacity(sKbd, 260, 0)
    DllCall("GetLocaleInfo", "uint", HKL
                           , "uint", 0x1001
                           , "str",  sKbd
                           , "uint", 260)
    Return sKbd
}

**Comment by jonaskohl** [comment]
The key components seem to be [`GetWindowThreadProcessId`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowthreadprocessid), [`GetKeyboardLayout`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayout) and [`GetLocaleInfo`](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getlocaleinfoa). I will put this on my backlog, although with low priority. Meanwhile, this will be available for anyone who is interested; pull requests are welcome!

**Comment by oleg-sgh** [comment]
Thanks
