### ISSUE TITLE
提示图标无法置顶显示

### ISSUE THREAD

**Issue by hxhxlhlh** [jonaskohl/CapsLockIndicator#105]
我在输入某些页面全屏的状态下，切换大小写，弹出的提示无法置顶，特别是我希望可以提示在屏幕中央无法实现，因为我的分辨率比较高，只是在右下角提示过于小经常看不到，不明显

**Comment by jonaskohl** [comment]
Please post issues only in English so that it is acccessible and everyone is able to understant its contents.

**Comment by hxhxlhlh** [comment]
Hi:
  I'm very sorry about the last email using Chinese, I think my problem has been solved, it may be the reason for the system abnormality that caused my prompt to not be able to place the desktop, now it is good, I really like this software, thank you very much for your efforts to develop it, wish you happy every day



Zuiren
China
