### ISSUE TITLE
Reset to default configuration

### ISSUE THREAD

**Issue by jfgarciamex** [jonaskohl/CapsLockIndicator#106]
Hi,

I think would be nice to have an option to reset configuration to default. Meanwhile, I wonder where configuration is saved and how I can reset to default? Thanks!

**Comment by jonaskohl** [comment]
The configuration file location is outlined in [this knowledge base article](https://cli.jonaskohl.de/kb/?a=settingsfile).

An option for resetting the configuration does not exist yet, but I will keep it in mind for a future release.

**Comment by jfgarciamex** [comment]
Thanks! That’s good enough! Sorry I missed!

Sent with a Spark
