### ISSUE TITLE
Show icons only when active

### ISSUE THREAD

**Issue by jonaskohl** [jonaskohl/CapsLockIndicator#107]
Add an option to show a tray icon only when its corresponding key is active.

*This suggestion was submitted by Alan Gordon via email*

**Original email text:**
> Hi!
> Very nice little utility! Thank you for creating this.
> I am not a programmer, so I could not create this myself..
> I have an idea that would make this more visually useful to me...
> 
> Could you create a new option in the General tab:  Show no icons when off/ only Show icon when on?
> (The checkbox could say, 'Hide icons when off')
> 
> This way, When I look at the screen, I either see an Icon (CapLock On) or I don't see an icon (CapLock Off).
> 
> This is how the keyboard lights work. Right now, I have to think about what red means, what green means..it is less intuitive, for me at least.
> 
> I hope you like this idea. Thank you for your consideration.
> 
> Alan Gordon

**Comment by piec** [comment]
Hi, I took a look at your source code and it seems to be implemented with `alwaysShowWhenActive` right?
https://github.com/jonaskohl/CapsLockIndicator/blob/f92c2b7cbbe29f2dc05a0545d30a11e37e01c2f3/CapsLockIndicatorV3/MainForm.cs#L842
