### ISSUE TITLE
Fn lock status & round border 

### ISSUE THREAD

**Issue by CarloHD** [jonaskohl/CapsLockIndicator#108]
- Add the possibility to trace the status of fn lock function present on some Dell laptop (maybe others laptop too?);
[link](https://www.howtogeek.com/235351/how-to-choose-whether-your-function-keys-are-f1-f12-keys-or-special-keys/) for "what i'm talking about" 

- Make the popup more beautifull with adding border radius

thks anyway for your little must usefull app

**Comment by jonaskohl** [comment]
The problem with FN lock is the fact that there is no standardized way of querying the state of the FN lock, as all vendors implement it differently, with some going as far as having it baked into the keyboard's firmware. That sadly means that this is not really feasible or possible to implement. 

The rounded corners are something I might look into, at least for Windows 11. This might be a challenge though, as Win32 windows are not really meant to handle transparency well. But I'll see what I can do.
