### ISSUE TITLE
how to change the language

### ISSUE THREAD

**Issue by glamgar** [jonaskohl/CapsLockIndicator#109]
Please help me.

I have download the file with trad but I don't no where to place it?

Ty

**Comment by jonaskohl** [comment]
Please refer to the translation page: https://cli.jonaskohl.de/!/translations#install-translations

> ## Install translations
> Extract the downloaded ZIP folder to your CLI installation directory. Make sure that the DLL is in a subfolder with the specific cultre name. For German for example the structure would be like this:
> 
> ```
> Installation Dir/
>   CLIv3-3.15.0.0.exe
>   de/
>     CapsLockIndicatorV3.resources.dll
> ```

**Comment by jonaskohl** [comment]
I assume the issue has been resolved, thus I will close this issue now.
