### ISSUE TITLE
Trojan virus detected

### ISSUE THREAD

**Issue by xoango** [jonaskohl/CapsLockIndicator#111]
Hello, I just updated to version 3.16.0.0 and Microsoft Windows 10 tells me that it contains a Trojan virus:

Trojan:Script/Sabsik.FT.A!mI
19/04/2022 9:33 (Active)

Why has this happened? In version 3.15.0.0 there was no such threat.

Thanks!.

**Comment by jonaskohl** [comment]
This is a false positive. I reported it to Microsoft

**Comment by ISA72** [comment]
Bonjour 
je viens de l installer mais mon anti virus fit que de le considerer comme un cheval de troie !!!!! c'est prenant

**Comment by jonaskohl** [comment]
Please only post issues in English to keep them accessible for everyone!

**Comment by lincoln90** [comment]
Have you had any feedback regarding malware that is still identified on VirusTotal?
I scanned again but a trojan is still detected.

![Screenshot 2023-02-08 230954](https://user-images.githubusercontent.com/32597256/217553290-64123a25-2ec0-41ce-8d56-9730c4cec25c.png)

MD5	9a7cabedbf071dedceb494c8b0bd4ec4
SHA-1	fa51411677453df28a9c66ec9d39b9a3e2da141c
SHA-256	04c36a520cea729650ebda59cbf1f5353999d478ff706914c3fccf5558fa2495
![Screenshot 2023-02-08 231104](https://user-images.githubusercontent.com/32597256/217553539-11d71f8f-6acc-4a72-aaff-e5f1939a8df2.png)

**Comment by jonaskohl** [comment]
MaxSecure and SecureAge seem to be very obscure AV programs which probably use basic heuristics to determine if an application is a threat or not. I can assure you that CapsLock Indicator is safe. If you don't trust the precompiled binaries, there is also always the option to compile CapsLock Indicator yourself from source
