### ISSUE TITLE
3.16 have error in win10 21H2

### ISSUE THREAD

**Issue by zengdabo** [jonaskohl/CapsLockIndicator#114]
I can run 3.15 without any errror.
But when I upgrade to 3.16, an error windows display,and show this error messages.
Please help check what happend,thanks!

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Specified cast is not valid.
   at CapsLockIndicatorV3.SettingsManager.Get[T](String key)
   at CapsLockIndicatorV3.IndicatorOverlay.ReapplyPadding()
   at CapsLockIndicatorV3.IndicatorOverlay..ctor(IndicatorTrigger trigger, Int32 timeoutInMs, Color bgColour, Color fgColour, Color bdColour, Int32 bdSize, Font font, IndicatorDisplayPosition position, Int32 indOpacity, Boolean alwaysShow)
   at CapsLockIndicatorV3.MainForm.ShowOverlay(IndicatorTrigger trigger)
   at CapsLockIndicatorV3.MainForm.UpdateTimerTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CapsLockIndicatorV3
    Assembly Version: 3.16.0.0
    Win32 Version: 3.16.0.0
    CodeBase: file:///E:/tools/system/CapsLock%20Indicator/CLIv3-3.16.0.0.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
CapsLockIndicatorV3.resources
    Assembly Version: 3.15.0.1
    Win32 Version: 3.15.0.1
    CodeBase: file:///E:/tools/system/CapsLock%20Indicator/zh-CN/CapsLockIndicatorV3.resources.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jonaskohl** [comment]
This is odd. Could you please upload your settings file? You'll find it at `%appdata%\Jonas Kohl\CapsLock Indicator\settings\any\usercfg`.

**Comment by zengdabo** [comment]
b:numIco=True
b:capsIco=True
b:scrollIco=False
b:numInd=True
b:capsInd=True
b:scrollInd=True
b:noIco=True
b:noInd=False
b:darkMode=False
b:hideOnStartup=True
b:checkForUpdates=False
b:upgradeRequired=False
b:alwaysShowWhenActive=False
b:firstRun=False
b:searchForUpdatesAfterResume=True
b:showNotificationOnAllScreens=False
b:supressEOLMessage=False
b:dontOverwriteApplicationOnUpdate=False
c:indBgColourActive=255;66;66;66
c:indFgColourActive=255;255;255;255
c:indBdColourActive=255;77;180;52
c:indBgColourInactive=255;66;66;66
c:indFgColourInactive=255;255;255;255
c:indBdColourInactive=255;180;52;77
f:indFont=Microsoft YaHei UI, 14pt, style=Bold
i:indDisplayTime=500
i:indOpacity=100
i:bdSize=14
s:versionNo=3.15.0.0
o:overlayPosition=MiddleCenter
s:customMessageCapsOn=
s:customMessageCapsOff=
s:customMessageNumOn=
s:customMessageNumOff=
s:customMessageScrollOn=
s:customMessageScrollOff=
s:selectedLanguage=en-GB
b:persistentOverlayCapsOff=False
b:persistentOverlayCapsOn=False
b:persistentOverlayNumOff=False
b:persistentOverlayNumOn=False
b:persistentOverlayScrollOff=False
b:persistentOverlayScrollOn=False
b:numIcoOnlyWhenActive=False
b:capsIcoOnlyWhenActive=False
b:scrollIcoOnlyWhenActive=False
o:indPadding=24;12;24;12

**Comment by jonaskohl** [comment]
I'm sorry but I can't reproduce this error

**Comment by zengdabo** [comment]
I found a solution,  reset  settings, and problem was fixed.
This problem can be reproduced, I start CL 3.15,change some settings, And
start 3.16.1.2, When I press capslock key, program cashed!
Jonas Kohl ***@***.***> 于2022年5月17日周二 02:02写道：
