### ISSUE TITLE
Language not updated

### ISSUE THREAD

**Issue by People-Sea** [jonaskohl/CapsLockIndicator#116]
Language not updated
<img width="669" alt="1652349592(1)" src="https://user-images.githubusercontent.com/70972819/168045465-2036d6b8-c3c8-4b2a-8c9d-319a6bca5d44.png">
<img width="573" alt="1652349630(1)" src="https://user-images.githubusercontent.com/70972819/168045577-febf3776-a2e4-4bdd-ac5f-133a909942b2.png">

**Comment by jonaskohl** [comment]
Please provide more information
