### ISSUE TITLE
Message when starting without internet connection

### ISSUE THREAD

**Issue by JOAOPUSERNET** [jonaskohl/CapsLockIndicator#117]
In the latest versions 3.16.1.0 and 3.16.1.1, this attached message appears when starting without internet connection.
With the internet connected this message does not appear.
In the previous versions this issue does not happen.

![Screen](https://user-images.githubusercontent.com/82158339/168824121-298801b1-4e36-4cc0-8883-8486aef6ffba.png)

**Comment by jonaskohl** [comment]
An update was released some time ago. I'm closing this now as the issue seems to be resolved
