### ISSUE TITLE
When activated: num, cap, scroll, stay showing, overlay on screen in Windows 10, e.g., remain showing notification, of any one of all three.

### ISSUE THREAD

**Issue by pcinternetit** [jonaskohl/CapsLockIndicator#119]
Troublesome and distracting, while wanting to see all screen. Is this how it is supposed to work, if not, can it be fixed. I have played with all settings, used CapsLockIndicator for years, am thinking it better in older versions.
Problem:
When activated: num, cap, scroll, never disappear, notification remain showing, overlay on screen in Windows 10, e.g., remain showing notification, of any one of all three.

**Comment by jonaskohl** [comment]
Please check the settings under `Notification` > `Display time`
