### ISSUE TITLE
support for NT 5.1 [feature-request]

### ISSUE THREAD

**Issue by andika207** [jonaskohl/CapsLockIndicator#120]
I request support for Windows XP.

regards

**Comment by jonaskohl** [comment]
Sadly, this won't happen as CapsLock Indicator depends on .NET Framework 4.7.1 which is only supported on Windows 7 or newer. Also, Windows XP is 21 years old at this point, so the amount of people using it is miniscule, so even if it was possible, supporting and maintaining it for Windows XP would not be feasible.
