### ISSUE TITLE
Feature Request : Customized Displayed String

### ISSUE THREAD

**Issue by LetterTung** [jonaskohl/CapsLockIndicator#121]
Hi there,
It's really a great project for me to optimize my experience when I'm coding.
Generally, I set the "display time" to permanent, then there's "Caps lock is off/on" string displayed on my screen. However, if the string can be customized(for example, "A" for caps lock on and "a" for off), no doubt that it will be much more perfect.
Thanks and Best Regards.

**Comment by jonaskohl** [comment]
This is already possible using the `customMessageNumOff`, `customMessageNumOn`, `customMessageCapsOff`, `customMessageCapsOn`, `customMessageScrollOff` and `customMessageScrollOn` settings under *Advanced Options*

**Comment by LetterTung** [comment]
hello Jonaskohl,
Sorry for the late reply. Yes that solved my problem. Thanks so much.
