### ISSUE TITLE
New Windows 10 x64 version 22H2(Version 19045) Enablement Package (KB5015684)

### ISSUE THREAD

**Issue by JOAOPUSERNET** [jonaskohl/CapsLockIndicator#137]
![CapsLock](https://user-images.githubusercontent.com/82158339/181026954-6277ea03-12e6-4765-acb9-ff2a89e687e3.png)
After installing the new 22H2 Enablement Package KB5015684 this message appears:
"This version of CapsLock Indicator (Version 3.16.1.2) is not supported. Please update to the latest version!"

KB5015684:

http://b1.download.windowsupdate.com/c/upgr/2022/07/windows10.0-kb5015684-x64_523c039b86ca98f2d818c4e6706e2cc94b634c4a.msu

Thanks.

**Comment by jonaskohl** [comment]
Is this still an issue?

**Comment by shinji257** [comment]
Getting a similar message on Windows 11.
![image](https://user-images.githubusercontent.com/261005/220824936-06c58297-88d9-468c-a9bc-8db0a5eb537a.png)
