### ISSUE TITLE
Icon package with missing icon

### ISSUE THREAD

**Issue by kiwichick888** [jonaskohl/CapsLockIndicator#140]
On the icons gallery page, the GeniusKB-dark pack by @Marin37 is missing the ScrollLock disabled icon. There are 2 CapsLock disabled icons instead. Sorry I'm posting here about it but I can't see how to contact him directly.

**Comment by Marin37** [comment]
Opened pull request at the [Icons repository](https://github.com/jonaskohl/CLI_Icons/pull/6), thanks for letting me know!

**Comment by kiwichick888** [comment]
You're welcome ☺️

**Comment by jonaskohl** [comment]
Next time, please report issues related to community icons over at [jonaskohl/CLI_Icons](https://github.com/jonaskohl/CLI_Icons)
