### ISSUE TITLE
One icon for all key

### ISSUE THREAD

**Issue by GrandSam** [jonaskohl/CapsLockIndicator#145]
Hi

thanks for your great tool, but one request : 

- ability to group notification icon into an unique one :
       for example could be like : a triangle one  (C-apslock S-crolllock and N-umlock)
                              C
                             S N
       Where the active key is green and inactive grey

So the notification area will only contains 1 icons not 3 for linked keys

Excuse my bad english ifg i'm not clear.

Kind regards from France

**Comment by jonaskohl** [comment]
I don't know if the 16x16 area we have available in a tray icon is big enough to convey the necessary information to the user. We'll probably have to do some mockups first. If anyone has a good draft for how such an combo icon could look, please lmk.
