### ISSUE TITLE
Update search error

### ISSUE THREAD

**Issue by jlitzie** [jonaskohl/CapsLockIndicator#15]
Hi,

I'm running version 3.6.1.0 and received the attached error this morning.
The application seems to be running fine other wise.

Thanks,

Jim

![image](https://user-images.githubusercontent.com/28759565/43199769-1e5985c0-8fe1-11e8-8d44-0b75f2af1f57.png)

**Comment by jonaskohl** [comment]
Seems to be an issue with https and TSL versions. I will work on a fix as soon as possible.

**Comment by jonaskohl** [comment]
This bug has been resolved in [Version 3.6.2.0](https://github.com/jonaskohl/CapsLockIndicator/releases/3.6.2.0).
