### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by mwilkesukf** [jonaskohl/CapsLockIndicator#155]
Hi,
I'm getting an error when the program is run, and it does not auto run after selecting 'Start on logon'.

Any ideas please?

![image](https://user-images.githubusercontent.com/107113622/217229527-61d9d61a-b0a3-40d1-b859-ea9be6529c9f.png)

**Comment by LangeHA** [comment]
I am receiving the same error message. You can clear the message and it still runs. I have "Check for updates" enabled. I also get that same error message when in click on the "Check for updates" button. Disabling "Check for updates" does not change the result in any way, the error still appears on startup and when the button is pressed. CLI v3.16.1.2 is installed and running on Windows 10 PRO 21H2, build 19044.2546 with all patches and feature updates installed.

**Comment by SeemorE68** [comment]
I to get the same error message would be nice to get a fix for it good little program otherwise.

**Comment by hsngrms** [comment]
I'm having same error. It wasn't there two days ago, IDK what triggered the issue.

**Comment by jonaskohl** [comment]
I'm using the endoflife.date API for checking OS versions in the backround. They pushed a breaking change to their API in endoflife-date/endoflife.date#2333 which caused my service endpoint to error out. Should be fixed now
