### ISSUE TITLE
Feature request: make display text configurable

### ISSUE THREAD

**Issue by aafulei** [jonaskohl/CapsLockIndicator#157]
Thank you @jonaskohl  for the nice application in the first place!

Is it possible to make display text configurable? For example, for capslock, I personally like

```
CapsLock ON
```

instead of the current

```
Caps lock is on
```

Is it possible?

**Comment by jonaskohl** [comment]
This is already possible using the following settings under *Advanced options*:

- `customMessageCapsOn`
- `customMessageCapsOff`
- `customMessageNumOn`
- `customMessageNumOff`
- `customMessageScrollOn`
- `customMessageScrollOff`
