### ISSUE TITLE
Option to hide CLI icon from tray

### ISSUE THREAD

**Issue by HYBRID-BEING** [jonaskohl/CapsLockIndicator#16]
Having an additional tray icon for application is redundant when indicator icons are present - please make it possible to access CLI options via indicator icons and add an option to hide CLI icon if any indicator is present (but show it if there are none).

**Comment by STaveras** [comment]
Here's an unofficial version that does just that: [3.7.1.1](https://github.com/STaveras/CapsLockIndicator/releases/tag/3.7.1.1un)

**Comment by jonaskohl** [comment]
Resolved in [3.7.2.0](https://clireleases.jonaskohl.de/releases/?tag=3.7.2.0)
