### ISSUE TITLE
Does the Indicator stay on as long as the lock is locked.

### ISSUE THREAD

**Issue by BlarneyTalker** [jonaskohl/CapsLockIndicator#170]
I constantly forget I have the caps lock on and start typing in all caps. I would like an indicator that stays on the screen the whole time the capslock key is locked.
Is that what this app does?

**Comment by heliomarpm** [comment]
Yes, it is possible

**Comment by heliomarpm** [comment]
> I constantly forget I have the caps lock on and start typing in all caps. I would like an indicator that stays on the screen the whole time the capslock key is locked.
> Is that what this app does?

Yes, it is possible

**Comment by Gluups** [comment]
Hello, On the notification tab, check CapsLock is : on.
On the top you can select how much time you want the notification to remain for when capslock is off. I advise you a short delay.
On the bottom you can select a place on the screen where the notification will be displayed.
On the right you can select colours, opacity, and if you wish a border thickness.
Do not forget to return to the general tab to click on Hide Window.

**Comment by 80H-d** [comment]
- open the program
- go to the advanced options tab
- select "advanced settings"
- check the box and select "ok"
- set "persistentOverlayCapsOn" to True by double-clicking the word "False" in the same row (default set to False)

When Caps Lock is on, the onscreen indicator should now persist.

**Comment by BlarneyTalker** [comment]
WOW. That works great.

Is there a way to move the indicator from the lower right to the upper left?



Jim O'Shea III

BlarneyTalker

ha en bra dag

Dia dhaoibh


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by 80H-d** [comment]
- open the program
- go to the notification tab
- in the bottom left is an "overlay position" section
- select which section you would like your indicators to populate
![image](https://github.com/jonaskohl/CapsLockIndicator/assets/145611979/9174d050-0437-45d2-954e-8223acbd44d6)

**Comment by BlarneyTalker** [comment]
The program is working, but I cannot find it to open it



Jim O'Shea III

BlarneyTalker

ha en bra dag

Dia dhaoibh


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by 80H-d** [comment]
- right click one of the icons in the system tray and select "show" to open the program
![image](https://github.com/jonaskohl/CapsLockIndicator/assets/145611979/849f7198-e5b0-4112-977f-dd2811372149)

- select the notification tab at the top of the program
![image](https://github.com/jonaskohl/CapsLockIndicator/assets/145611979/b0c80235-e219-462e-ae7f-d724afdf6556)

- overlay position can be selected in the bottom left
![image](https://github.com/jonaskohl/CapsLockIndicator/assets/145611979/5ef67a94-0285-4424-880a-502996efd83c)

**Comment by 19e2k67** [comment]
![image](https://github.com/jonaskohl/CapsLockIndicator/assets/102461738/c26eaad0-16fe-4c4b-a48c-126811a6ca6d)
It's a bit small on the 2K monitor, how can I turn up this prompt box?

**Comment by bxf999** [comment]
On 3.16.1.2, WIn11 Pro x64 22H2

The "Show persistent overlay when..." function works, until it gets reset by itself. Several times I select these boxes, and the function works. At some future point, the indicator disappears, and looking at the Notification settings, the boxes are cleared.
Nobody esle uses this computer. I'm not sure if this happens across a reboot.

**Comment by 80H-d** [comment]
Persistent overlay works until a lock function without a persistent indicator attached is activated.

There is only one slot in which to display an indicator.

So, let's say you have persistent caps lock, but NOT persistent num lock.

1. You activate caps lock. The caps lock indicator appears.
2. You activate num lock. The num lock indicator appears, overriding the caps lock indicator.
3. The num lock indicator disappears after a short delay.
4. Currently, there is no instruction in the program for the caps lock indicator to reappear.

I actually submitted a request to add the feature to display multiple persistent indicators and/or not have indicators override one another like this! Hopefully soon eh?

**Comment by bxf999** [comment]
Thanks for the suggestion, but I typically have all three indicators on, so no, your scenario does not apply. Also, note that the check marks in relevant selection boxes are cleared (not by me), so it's not just a matter of the indicators not coming up.

**Comment by bxf999** [comment]
It appears that the indicators get reset during a reboot.

**Comment by bxf999** [comment]
For what it's worth, the problem disappeared. I am not aware of having done anything to change the behavior, so we are good, thank you.
