### ISSUE TITLE
More customization for indicator visuals/placement

### ISSUE THREAD

**Issue by 80H-d** [jonaskohl/CapsLockIndicator#171]
- ~~add windows key lock indicator (gamers, what a group)~~
- allow multiple onscreen indicators to persist simultaneously (ie caps lock toggle will not override persistent num lock indicator)
- make persistent indicators have dynamic position to mitigate problems with peeking hidden taskbar (currently remains static when peeking taskbar): 
![Caps indicator static position with hidden, unpeeked taskbar](https://github.com/jonaskohl/CapsLockIndicator/assets/145611979/2b38df18-abf8-4841-a782-f578dfd34628)
![Caps indicator static position with hidden, peeked taskbar](https://github.com/jonaskohl/CapsLockIndicator/assets/145611979/25893e5b-a448-4a35-8d3a-3f0cd6e2c1fb)
- allow indicators in multiple spots per screen (per-spot definable visual settings) based on open programs/program location (eg discord in top left corner and msword in center middle might prompt on-screen indicators to display in both areas—user-definable parameters)
- lock-specific indicator visual customization (eg green for caps, blue for scroll, red for num, also separately definable for each spot per above point)
- allow more granular positioning of indicators
- allow separation of indicator position, such as caps lock bottom right, num lock top right, etc
- allow customization of system tray icon colors to increase visual differentiation between on and off state (eg entire background + border turns red or green with black letter)

**Comment by 80H-d** [comment]
man come on man please

**Comment by qb20nh** [comment]
Windows key lock functionality is provided entirely within keyboard hardware and cannot be spied from any application software.
I propose to change the issue title to: More customization for indicator visuals
