### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by WaldekMM** [jonaskohl/CapsLockIndicator#177]
Hello
does anybody now howcto turn off the sound notification when CapsLock/NumLock/ScrollLock is on/off ?

**Comment by jonaskohl** [comment]
CapsLock Indicator does not play any sound when turning on or off Caps Lock, Num Lock or Scroll Lock. The sound must come from an OEM software or the OS directly

**Comment by WaldekMM** [comment]
OK, thank you very much!


czw., 29 lut 2024 o 09:23 Jonas Kohl ***@***.***> napisał(a):
