### ISSUE TITLE
Capslock Indicator

### ISSUE THREAD

**Issue by pauljstuart** [jonaskohl/CapsLockIndicator#18]
Hi there,

I am using Capslock Indicator, and I like it - thanks!

A suggestion.  It would be good if you you could mark the indicator 'always on top'.  At the moment the indicator appears to be on top of other windows.  But at other times it's not visible.  Or perhaps that's a bug.  For instance, I use Citrix Receiver, to connect to a virtual windows desktop.  And when I do that the indicator is not visible on the screen.

regards

paul Stuart

**Comment by jonaskohl** [comment]
This is a thing with Windows. The overlay already has the `TopMost` flag set to `true`, so there is sadly nothing I can do about this.
