### ISSUE TITLE
Windows 11 24H2 not supported warning

### ISSUE THREAD

**Issue by lothkang** [jonaskohl/CapsLockIndicator#183]
I've just downloaded CapsLockIndicator and it says that Windows 11 24H2 is no longer supported by Microsoft and that CapsLockIndicator is going to drop support for it soon. Windows 11 24H2 is not only still supported, but it's the latest stable Windows release to date.

![Képernyőkép 2024-06-30 143017](https://github.com/jonaskohl/CapsLockIndicator/assets/23418584/aeee6906-92d9-4772-b592-6f7036efc061)

**Comment by SmellsSmell** [comment]
I don't know how Windows Update works. but I have 8 computers in this house. And I just checked updates on all of them, but none of them are running 24H2. So I don't know if it got released early in the UK or what. But unless the author's computer happens to have that update, I don't think they can fix it until they get it...

**Comment by SmellsSmell** [comment]
> I don't know how Windows Update works. but I have 8 computers in this house. And I just checked updates on all of them, but none of them are running 24H2. So I don't know if it got released early in the UK or what. But unless the author's computer happens to have that update, I don't think they can fix it until they get it...

I think this is just Software gore because Windows just updates whenever it feels like it wants to update. Microsoft is great tbh...

**Comment by xgdgsc** [comment]
It' s easy to get 24h2 at release preview channel. I use arm so I get that for the improved emulation performance. The author might be able to fix the bug even without updating because it might be just some string comparison condition issue.
