### ISSUE TITLE
Can it be on top of Fullscreen DirectX Applications?

### ISSUE THREAD

**Issue by SmellsSmell** [jonaskohl/CapsLockIndicator#186]
Just curious if you can make it on top of Fullscreen games. I hate when I type something in-game and it was all caps but I pressed enter before I noticed...

**Comment by KpWC** [comment]
As a gamer in Fallout London, I would love to see the overlay on top of a fullscreen game so that I can keep track of whether I'm running or walking.  ;-) Thank you.
