### ISSUE TITLE
Feature Request: Hide CLI options window when hitting close window button control

### ISSUE THREAD

**Issue by Yetoo1** [jonaskohl/CapsLockIndicator#19]
It would be great if the close window window control would just hide the window instead of exiting out of the application. This is especially true when you have just been updating the startup processes rather than downloading a new executable. This leads to redundant updating when accidentally hitting the close window control when expecting it to just hide the window. Also, I expect that an option window for a service to be independent from the service itself except for the options within the window. I was expecting the window to be an interface to the application and not the service itself which is closed like a GUI application.

**Comment by jonaskohl** [comment]
This was the case until [3.3.2.0](https://github.com/jonaskohl/CapsLockIndicator/releases/tag/3.3.2.0), but it prevented the computer from properly shutting down when Windows tried to close all open programs, and it would lock up. So I removed that feature.

**Comment by Yetoo1** [comment]
Couldn't you use CloseReason?

**Comment by Yetoo1** [comment]
I created a pull request that has behaviour as described in my request. This shouldn't lock up windows and it allows the program to function when the close window window control is pressed.

**Comment by jonaskohl** [comment]
Implemented in [3.7.0.0](https://github.com/jonaskohl/CapsLockIndicator/releases/tag/3.7.0.0)
