### ISSUE TITLE
Program instantly terminates among open without display.

### ISSUE THREAD

**Issue by brendeni1** [jonaskohl/CapsLockIndicator#194]
No compatibility or admin settings fix this.

Replication: Open CLI and watch it instantly close.

Windows 11 23H2

**Comment by herrblitzkrieg** [comment]
Same issue here. Found no fix so far :(

**Comment by herrblitzkrieg** [comment]
Found the fix: Delete "%APPDATA%\Jonas Kohl\CapsLock Indicator\settings\any\usercfg" and now relaunch CapsLockIndicator.

I realized this when debugging the app and observing how the internal Settings Manager kept causing these exceptions at various locations when reading the setting file.

**Comment by brendeni1** [comment]
> Found the fix: Delete "%APPDATA%\Jonas Kohl\CapsLock Indicator\settings\any\usercfg" and now relaunch CapsLockIndicator.
> 
> I realized this when debugging the app and observing how the internal Settings Manager kept causing these exceptions at various locations when reading the setting file.

Can confirm, working.

I probably should have done some debugging before buying an app to perform the same functionality off of the MS store... I guess I have a backup now. 😅

Thanks!
