### ISSUE TITLE
Problem with update message window

### ISSUE THREAD

**Issue by joanfg** [jonaskohl/CapsLockIndicator#2]
Hello,

First of all thanks for the creation of the indicator, my computer lacks a proper indicator and I use yours instead. When using the last version, I found the problem that t the updating windows keeps popping out every time I restart my computer, even though the last version is already installed.
I hope you can manage to solve it and it runs without the problem in future versions. 

Best regards,
Joan

**Comment by jonaskohl** [comment]
Can you please post a screenshot of the dialog?

**Comment by jonaskohl** [comment]
I am closing this issue as I don't seem to get any further response.
