### ISSUE TITLE
Append CLI to restart text on button in the download dialog to make more clear what is being restarted. 

### ISSUE THREAD

**Issue by Yetoo1** [jonaskohl/CapsLockIndicator#23]
It would be great if CLI or some other text was appended to the restart text in the download dialog box to make more clear that the computer isn't going to restart. This is intended to reduce the number of tickets users initiate when seeing the download dialog and being not sure if they are going to be restarting their computer or not.

**Comment by jonaskohl** [comment]
I will include this in the next update
