### ISSUE TITLE
Option to hide system CLI program icon in system tray?

### ISSUE THREAD

**Issue by gate1975mlm** [jonaskohl/CapsLockIndicator#24]
I would really like to hide the CLI program icon from the system tray.

But of course I would need a way to open the CLI settings so how about adding a CLI shortcut in the Start Menu All Apps List?

Would this be possible in the future?

Thanks

**Comment by jonaskohl** [comment]
As CapsLock Indicator is a portable application, it won't get a start menu shortcut. Thus the tray icon is necessary. If you want to hide the icon, you can disable the option _Always show all icons in the notification area_ under _Settings_ > _Personalization_ > _Taskbar_ > _Notification area_ > _Select which icons appear on the taskbar_. Then turn off _CapsLock Indicator_ in the list below the aforementioned option.
