### ISSUE TITLE
CLI installer?

### ISSUE THREAD

**Issue by gate1975mlm** [jonaskohl/CapsLockIndicator#25]
Any chance of making an installer for CLI?

So this way it installs to my C drive and then I can launch it from the start menu like most other programs?

**Comment by jonaskohl** [comment]
CapsLock Indicator won't get an installer. The appeal of CapsLock Indicator is that it is portable and no installation is necessary. If you still want to add it to your start menu, you can follow [this guide by Windows Central](https://www.windowscentral.com/add-app-shortcuts-start-menu-manually-windows-10).
