### ISSUE TITLE
Can't get custom icons to work!

### ISSUE THREAD

**Issue by gate1975mlm** [jonaskohl/CapsLockIndicator#26]
I followed the directions from the following web site but when I click Caps, Scroll or Number lock key I am not seeing my custom icons. All am seeing it the default one.

https://cli.jonaskohl.de/!/icons

Thanks

**Comment by jonaskohl** [comment]
Huh, it is working for me. Please make sure CapsLock Indicator is executed inside the folder where your icons are located (most likely a problem when using shortcuts or batch scripts). Also make sure the icons are valid [Windows ICO](https://en.wikipedia.org/wiki/ICO_(file_format)) files.

**Comment by gate1975mlm** [comment]
Here are the icons I am trying to use.
[ico icons.zip](https://github.com/jonaskohl/CapsLockIndicator/files/2784554/ico.icons.zip)

**Comment by jonaskohl** [comment]
Your problem is that you files have a double extension, so they are named `num0.ico.ico` etc. This might be because you have file extensions turned off. I suggest you enable it in Windows Explorer in the ribbon menu under _View_ > _File name extensions_

**Comment by jonaskohl** [comment]
I am closing this now as I recieved no response.
