### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by ktal4** [jonaskohl/CapsLockIndicator#27]
Is it possible to make the background transparent?  So that all we see is a text notification? I can see how to make it white but not transparent.  I'd like to be able to set it so that the only time I see the notification is when caps lock is on.

**Comment by jonaskohl** [comment]
This is going to be quite a challange, because I'm using a normal GDI+ Form to draw the notification, which sadly does not provide alpha transparency out of the box (using `TransparencyKey` would look ugly). However, I'm going to try my best and see what I can do!

**Comment by ktal4** [comment]
That would be great!  Thanks for trying.

**Comment by verwischt** [comment]
Hello. I would like a feature like that too. Is there anything new related to this request?
