### ISSUE TITLE
Num Lock, Caps Lock and Scroll Lock labels should be translatables

### ISSUE THREAD

**Issue by Dric** [jonaskohl/CapsLockIndicator#28]
Hi,

In French, `Num Lock` is translated as `Verrouillage numérique` for example (or `Verr. Num.` for short label). Same for `Caps Lock` ( `Verrouillage majuscules`, `Verr. Maj.`) ans `Scroll Lock` (`Arrêt défilement`, `Arrêt Défil.`). 
But these labels are currently not translatables into another language.

Thanks

**Comment by jonaskohl** [comment]
I'm going to add this to the next update and I'm going to add this to the [translation page](http://translate.cli.jonaskohl.de/collaboration/project?id=301500) as soon as possible!

**Comment by jonaskohl** [comment]
I'm sorry, but I don't quite know what you mean. Everything seems to be translated. Maybe your language extension may be out of date as they do not get updated automatically. Please try [updating your language extension](https://cli.jonaskohl.de/!/translations#download-translations)!

**Comment by Dric** [comment]
I tried to download new release and the translation file in French. When opening CApsLockIndicator, all labels are translated.

But the tooltips in taskbar stay in English (I tried to screenshot it, but the tooltip hides before the screenshot is taken)

Also, the link in the download page to the french translation dll is leading to the english file (I replaced `en` by `fr` to get it).

**Comment by jonaskohl** [comment]
The link has been fixed now, sorry about that! To screenshot the overlay, try pressing `Prt Sc` key (could be something like `Imp. écr.` in French) to copy the whole screen to the clipboard. You then can paste this into an image editing software like e.g. Paint and save it as an image. Alternatively, if you have Windows 8.1 or 10 you can press the Print Screen key together with the Windows key to directly save a screenshot as image.

**Comment by Dric** [comment]
Here is a screenshot :
![CLi-screenshot](https://user-images.githubusercontent.com/1764971/57931391-a2abe280-78b8-11e9-9cd0-9eb17f2a138f.png)

As you can see, the french translation is applied to CLI, but the taskbar icons tooltips are not translated (it should be "Verr. Num." instead of "Num Lock" in French, for example)

**Comment by K08official** [comment]
I hope it's not too late, but you can make your own icons like this:
https://cli.jonaskohl.de/!/icons
It's a bit of a workaround, but it solves your problem ;).

**Comment by Dric** [comment]
In fact no, because that's not the taskbar icons that bother me, but more the tooltip label.

I did a PR #37 , but I'm not able to test it...

**Comment by K08official** [comment]
Oh now I see...

**Comment by jonaskohl** [comment]
This issue hasn't had any updates in over two years. I will close this now
