### ISSUE TITLE
Disable Notification when send to tray

### ISSUE THREAD

**Issue by sinky** [jonaskohl/CapsLockIndicator#29]
The Notification when the main window is send to tray is really annoying. This Notification appears also when the program is set to hide on startup (every time).

**Comment by jonaskohl** [comment]
I'm going to finally remove this in the next version. That popup was still ment for pre-Windows 10 usage and is now obsolete.

**Comment by jonaskohl** [comment]
Resolved in [3.7.2.0](https://clireleases.jonaskohl.de/releases/?tag=3.7.2.0)
