### ISSUE TITLE
Avast detecting as Virus

### ISSUE THREAD

**Issue by acicovic** [jonaskohl/CapsLockIndicator#3]
Hi,

When checking the checkbox to run at log on, avast detects CLI as a virus (IDP.ALEXA.51). I guess that this is triggered by the behavior shield. The file is the one downloaded from your site.

You could probably submit the file to them so they can fix it...

**Comment by jonaskohl** [comment]
As suggested by you I have now contacted Avast to add CapsLock Indiactor to their white list.
