### ISSUE TITLE
Notification settings: "Text colour activated" appears twice

### ISSUE THREAD

**Issue by BruceFraser1** [jonaskohl/CapsLockIndicator#32]
Sorry, I should have mentioned this before your latest update.
In the Notification Settings window, "Text colour activated" appears twice. The second one should be "... not activated," and it functions that way.
Thanks for changing the Windows notification in yesterday's update!

**Comment by jonaskohl** [comment]
Resolved in [3.7.3.0](https://github.com/jonaskohl/CapsLockIndicator/releases/tag/3.7.3.0)
