### ISSUE TITLE
Save "Notification settings"

### ISSUE THREAD

**Issue by BruceFraser1** [jonaskohl/CapsLockIndicator#33]
Hi Jonas,
Wonderful program! Thank-you.
So wonderful, in fact, that I grieve every time an update comes, because I have to go through the process of renewing the Notification Settings. I change the position, and all the colour options.
SUGGESTION: It would be nice if users could save and restore the Notificiation Settings. Or--even better--they would be retained during an update.

**Comment by jonaskohl** [comment]
This sadly is a limitation of .NET's settings feature. Version 4 will address this issue

**Comment by jonaskohl** [comment]
A potential fix for this has been implemented in version 3.8.0.1
