### ISSUE TITLE
Could I change the letter "C" on the icon

### ISSUE THREAD

**Issue by mxhx** [jonaskohl/CapsLockIndicator#34]
Could I change the letter "C" on the icon, like "A"?  "C" is not easy to recognize the status.
Caps Lock on is ”A“, Caps Lock off is ”a“.

**Comment by jonaskohl** [comment]
Since version 3.6.0.0, CapsLock Indicator allows you to load custom icons. Please see [the page on icons on cli.jonaskohl.de](https://cli.jonaskohl.de/!/icons). You could create icons to your own liking and load them in.

**Comment by mxhx** [comment]
> Since version 3.6.0.0, CapsLock Indicator allows you to load custom icons. Please see [the page on icons on cli.jonaskohl.de](https://cli.jonaskohl.de/!/icons). You could create icons to your own liking and load them in.

**Comment by mxhx** [comment]
It works, But when I opened the PC and the

**Comment by mxhx** [comment]
It works, But when I opened the PC and this software start on login, The icon also the default 'c', I should restart it then the icon will be changed.

**Comment by mxhx** [comment]
[icon.zip](https://github.com/jonaskohl/CapsLockIndicator/files/3264185/icon.zip)

**Comment by mxhx** [comment]
The 'CapsLock Indicator' should be restarted every time before icons take effect. 
win7 sp1 x64
