### ISSUE TITLE
Window opens for less than second then set to hide

### ISSUE THREAD

**Issue by Yetoo1** [jonaskohl/CapsLockIndicator#38]
When I set Capslock Indicator to hide and start on Windows start up, the Capslock Indicator window shows up for less than second before it hides. I noticed this on a slow dual core 1 GHz Windows 7 laptop. I'm not sure if this can be fixed because it looks like InitializeComponent() is the culprit, but may be needed first to read properties to hide. I haven't tested yet.

**Comment by jonaskohl** [comment]
This is a limitation with the WinForms implementation and would be difficult to fix. This will be addressed in version 4 (which uses WPF for UI)

**Comment by Yetoo1** [comment]
This appears fixed in the latest update. I'm assuming it's the added else statement (119-123) in MainForm.cs and if so, why does this fix it?

**Comment by jonaskohl** [comment]
Basically, I'm setting the MainForm's opacity to 0 and hide it from the taskbar ([MainForm.cs:71-72](https://github.com/jonaskohl/CapsLockIndicator/blob/7794a2a409da4279d92b60172b5179cc74d01c62/CapsLockIndicatorV3/MainForm.cs#L71-L72)) and if the window is *not* set to auto-hide or it gets shown manually later, I'm reverting these settings to normal (opacity 1, show in taskbar, [MainForm.cs:121-122](https://github.com/jonaskohl/CapsLockIndicator/blob/7794a2a409da4279d92b60172b5179cc74d01c62/CapsLockIndicatorV3/MainForm.cs#L121-L122))

**Comment by jonaskohl** [comment]
I'm closing this now, as the issue seems to have been fixed with version 3.8.0.0
