### ISSUE TITLE
Introduce option to keep overlay visible for as long as lock-key is active

### ISSUE THREAD

**Issue by arnovdk** [jonaskohl/CapsLockIndicator#41]
It would be nice to have an option to keep the overlays always on for as long as the appropriate lock-key is active.

As in:
- numlock on -> overlay always visible
- numlock off -> overlay always invisible

(same for scrolllock and capslock)

**Comment by jonaskohl** [comment]
I've added this to my backlog for version 4!

**Comment by jonaskohl** [comment]
This has been implemented in 3.9.0.0. I'm closing this now. If your issue has not been solved, please reopen.
