### ISSUE TITLE
Could you please create a new translation project for Brazilian Portuguese, so I can contribute?

### ISSUE THREAD

**Issue by MarcosAlvesVieira** [jonaskohl/CapsLockIndicator#42]
Hi, I would like to know if anyone could create a fork of the European Portuguese translation, renamed to Brazilian Portuguese, so I can contribute adjusting a few terms to my mother language, please?

**Comment by jonaskohl** [comment]
Brazilian Portuguese has been enabled at [translate.cli.jonaskohl.de](http://translate.cli.jonaskohl.de)

**Comment by MarcosAlvesVieira** [comment]
Translation finished. Can you make the .dll file and add it to the download page?

**Comment by jonaskohl** [comment]
I have created the DLL file for Brazilian Portuguese: [Link](https://cli.jonaskohl.de/!/translations#download-translations)

**Comment by MarcosAlvesVieira** [comment]
Thanks. I've downloaded and tested it and everything looks good, except for some sentences which are breaking lines.

Please see the red highlighted areas in this image: [https://imgur.com/a/JiAyZH2](url)

I would like to suggest, for next versions, that the application interface be a little bit wider.
