### ISSUE TITLE
Multiple monitor not supported

### ISSUE THREAD

**Issue by AdmiralJensen** [jonaskohl/CapsLockIndicator#44]
Indicator message only on monitor 1
![image](https://user-images.githubusercontent.com/569662/76703991-ea9bc180-66a3-11ea-93d8-4ad93c3118de.png)

**Comment by jonaskohl** [comment]
This is a limitation of the current implementation. This is on my backlog and will be fixed in version 4.

**Comment by jonaskohl** [comment]
This was implemented in version 3.8.0.0
