### ISSUE TITLE
CapsLock Indicator icon not always appearing when no icon is enabled

### ISSUE THREAD

**Issue by DaveH1** [jonaskohl/CapsLockIndicator#45]
Great program, and does just what it says on the tin, but I have a problem!
I switched off all the icons, and set it to just show me on a popup when the caps lock setting is changed. I also set it to start at logon and hide the window.
All well and good, but how do I then get the settings window back again to change a setting?
If I run the program again it just says it's already running, and if I close it with Task Manager and run it again of course it runs and immediately hides itself!
I had to edit the configuration file to stop it hiding itself.
I now see that the icons allow you to get the window back, but that's no good if you have them all switched off!
Cheers, Dave.

**Comment by jonaskohl** [comment]
If you have disabled every key icon, there should be a new icon with the CapsLock Indicator logo in your system tray (see below). If you right click, you should get the usual "Show" and "Exit" options. Hope this helps!

![image](https://user-images.githubusercontent.com/23175424/77258255-ca5a9c80-6c79-11ea-9d37-ba159cde3407.png)

**Comment by DaveH1** [comment]
Ah thank you, that would make sense but I'm sure the icon wasn't there.
I have Windows 8.1 settings set to always show all taskbar icons and notifications, so it should have been there.
Thanks for the incredibly quick reply BTW!
Cheers, Dave.

**Comment by DaveH1** [comment]
OK, it seems that with the setting set to show all icons, it doesn't appear.
However, if I uncheck that, and set the CapsLock icon to show everything, it appears, and then "sticks" when I switch "show all icons" back on again.
The only problem now is that I have a blue taskbar, and the icon is virtually invisible!

**Comment by jonaskohl** [comment]
Ah, I see the problem. I'm currently working on version 4, and I'll write that on my list. The icon for the next version will probably be white or black, depending on system theme (although I'm not 100% sure yet). The icon not appearing is definitely a bug and will be fixed in v4.

**Comment by jonaskohl** [comment]
I'm also going to change the title of this issue to describe the bug you have mentioned

**Comment by DaveH1** [comment]
Thanks Jonas!

**Comment by DaveH1** [comment]
Sorry Jonas, just one other thing, perhaps for version 4?!
To me, the normal mode for caps lock is off, so as green means OK to me, and red means not OK, I changed the border of the notification to be green when caps lock is off, and red when it's on.
I've now noticed that the border of the caps lock system tray icon is still the other way around, and there seems to be no way of changing it, unless I've missed something.
Any chance that could be addressed in the next version?
Cheers, Dave.

**Comment by jonaskohl** [comment]
You could create custom icons and load them into CapsLock Indicator. Please see [this page](https://cli.jonaskohl.de/!/icons) for more information

**Comment by DaveH1** [comment]
I'll look into that, thanks Jonas!
I still think that caps lock at least should be green for off and red for on by default!
Thanks again, Dave.

**Comment by DaveH1** [comment]
One other thing I've noticed BTW is that the formatting of the text in the settings window falls to pieces, at least on Windows 8.1, if you use anything other than 100% scaling.
I tried to make things a bit bigger on my netbook screen, and even going to 110% a lot of the text doesn't fit in the boxes properly any more.

**Comment by Yetoo1** [comment]
> I'll look into that, thanks Jonas!
> I still think that caps lock at least should be green for off and red for on by default!
> Thanks again, Dave.

For the sake of other perspective, I disagree with that being default. The way I see it, green means go and red means stop. To me, the best way this can be applied in this instance is if go means caps lock is on and red it is stopped. I just feel that's more intuitive and pragmatic.

**Comment by DaveH1** [comment]
OK, fair enough!
I still find it quite unbelievable that some computer manufacturers (Asus, I'm looking at you!) don't think it's necessary to have any indication at all on some models as to the state of things like the caps lock.
They even have an on-screen information popup program of their own which gives you information about things like whether the touchpad is disabled with the function keys or not, but something as basic as the caps lock state, no!
Thank goodness guys like you have addressed this!

**Comment by jonaskohl** [comment]
> One other thing I've noticed BTW is that the formatting of the text in the settings window falls to pieces, at least on Windows 8.1, if you use anything other than 100% scaling.
> I tried to make things a bit bigger on my netbook screen, and even going to 110% a lot of the text doesn't fit in the boxes properly any more.

That is because CapsLock Indicator uses WinForms, which is handles DPI scaling abysmally poorly. That is one of the reasons why I'm switching over to WPF, as it handles DPI scaling a thousand times better.

>I still find it quite unbelievable that some computer manufacturers (Asus, I'm looking at you!) don't think it's necessary to have any indication at all on some models as to the state of things like the caps lock.

This is why I started this project in the first place. Back then I also had a laptop which didn't have any indication for caps lock and num lock whatsoever.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Hi again Jonas,
Thanks for the new versions, but when I tried to do an in-place update on both of them, I just got a .NET error window.
Downloading the new version and installing over the old one works fine.
Cheers, Dave.

**Comment by DaveH1** [comment]
Oops, so sorry about the multiple posts, I hope you didn't get a notification for all of them!
That will teach me to use an old version of Firefox, it looked as if my posting was failing, but it wasn't, and every time I tried again it was posting duplicates!
I have now deleted them all.
