### ISSUE TITLE
Update Server Down?

### ISSUE THREAD

**Issue by DaveH1** [jonaskohl/CapsLockIndicator#48]
Hi Jonas, is your update server down at the moment?
I have CLI set to automatically check for updates, and on every boot for the last couple of days I'm seeing a popup saying "An error occurred when searching for updates: The remote server returned an error: (403) Forbidden."
Cheers, Dave.

**Comment by jonaskohl** [comment]
This was my fault, sorry! I accidentally messed up the server configuration. It should work again now!

**Comment by DaveH1** [comment]
Yes, fine now thanks!
