### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by lanehoy** [jonaskohl/CapsLockIndicator#49]
How is the application uninstalled?

1. I do not find it in the installed applications list
2. Can't find installation folder.
etc.

**Comment by jonaskohl** [comment]
As CapsLock Indicator is a portable application, it is just a stand alone .exe file. To remove CapsLock Indicator from your computer, first make sure the checkbox next to `Start on logon` is *unchecked*. Then, exit CapsLock Indicator and lastly just delete the .exe file!

I hope I could help you. If so, please close this issue, if no other questions arise.

**Comment by jonaskohl** [comment]
Closing this because no I did not receive further feedback in 9 days and I assume the issue has been solved. If not, please reopen this issue.
