### ISSUE TITLE
Checking updates ON/OFF

### ISSUE THREAD

**Issue by ANDREW007CZ** [jonaskohl/CapsLockIndicator#5]
Hello,

thank you for making this utility.

I only have a little problem. Could it be possible to turn off checking for update?
Explaining why: 
The utility shall monitor keyboard input, is it alright? I am worried that if this utility monitors keyboard input and can connect to internet, it can as well send all input records from my keyboard to your server/anywhere on internet. I cant thrust it, please dont take this personally.
So I deny internet acces for Capslock indicator and then I am getting errors whenever I start my computer (start Capslock indicator). It is a bit frustrating.

Could this be possible in next update, please?

![obrazek](https://user-images.githubusercontent.com/26521196/34915913-0c292d9a-f92f-11e7-9a8c-dedfd28605ad.png)

**Comment by jonaskohl** [comment]
I will implement this in the next update.
Also, there is no need to be worried. CLI is **not** a key logger. You can always look at the source code.

**Comment by ANDREW007CZ** [comment]
Great! Thank you much!
