### ISSUE TITLE
Problem when displaying CLI notification after update

### ISSUE THREAD

**Issue by VladWinner** [jonaskohl/CapsLockIndicator#50]
Windows 10 v. 2004, 100% DPI
All settings were reset after the update (3.7.3.0 → 3.8.0.0), but I configured the same way.

![sample](https://user-images.githubusercontent.com/13555921/89619133-21ae8180-d896-11ea-93db-0fb5dbf75bc1.png)

**Comment by jonaskohl** [comment]
This is probably a side effect of setting the `AutoSize` mode of the indicator form from `Font` to `DPI`. This is a bug and I'll look into it!

**Comment by jonaskohl** [comment]
This should now be fixed in version 3.8.0.1. Please let me know if further issues occur!
