### ISSUE TITLE
Could you add an image of what the result looks like

### ISSUE THREAD

**Issue by fxpar** [jonaskohl/CapsLockIndicator#51]
Hi, 
Before installing or downloading, it would be nice to see what it does.

Is there an image of what the icons or the message looks like ? (is it a message as an overlay, is it an icon in the system tray, is it a colored icon, does it take a lot of space in a screen...).
Would be nice to have at least one here or on your website too in the overview section (not just an image of the .
Best Regards

**Comment by jonaskohl** [comment]
I added an additional image to the website. Hope that helps!

**Comment by fxpar** [comment]
You are really, really fast 👍 
Super!
