### ISSUE TITLE
V 3.8.0.1 Does not work with Windows 10 64bit

### ISSUE THREAD

**Issue by BazzaBoy** [jonaskohl/CapsLockIndicator#55]
I just downloaded the latest version 3.8.0.1, but it won't work with Win 10 Home Edition, 64 bit (nothing happens when I double-click the exe file).

Reverted back to v3.6.1.0

Please suggest a solution. Thanks.

**Comment by TheYeGh** [comment]
Hi there
OS - Windows 10/64bit tourn on AMD/PhenomII965 with 16GBDDR3and AMDGPU
clicking on any of buttons (caps, num, scroll) give this reaction
OS up on date, all the drivers also
![aa](https://user-images.githubusercontent.com/70953888/92475746-2e4c2f80-f1de-11ea-8f40-681bc306e6b1.jpg)

**Comment by jonaskohl** [comment]
This is very weird. Is there any crash log in Windows Event Viewer related to this?

**Comment by jonaskohl** [comment]
@TheYeGh Please do not comment on an existing issue with a separate problem. Please open a new issue instead.

**Comment by TheYeGh** [comment]
I have no political correctness - don't count on mercy - I'm too old to
lick your ass because someone said so
and you think I will keep a useless program, its remnants, logs for over 3
weeks and wait than you will answer me kindly ??
you are wrong - your program is wrong, it does not work with Windows10 /
64bit MSDN A20H, previously A20B, and if it already works, it is wrong
this is your program - you give it for free but unfortunately it is
underdeveloped, it has bugs that you ignore - as an IT specialist you are a
failure - so don't be surprised that people will ignore you

czw., 24 wrz 2020 o 11:44 Jonas Kohl <notifications@github.com> napisał(a):

**Comment by jonaskohl** [comment]
@TheYeGh 
This is not a place to start an argument nor to leave such inappropiate insults. I am a high school student who develops CapsLock Indicator in my spare time. Thus, there can be long periods of time where I don't have the time to work on this project. I apologize if the update cycle is too slow. But I cannot tolerate your poor manners and behaviour. I have reported your abusive comment and if you don't start to behave better, I'll sadly have to block you. It is okay if you're not happy with the update rate, but I ask you to keep yourself and your words under control. I also think it is quite miserable to call a stranger on the internet, who invests a lot of their spare time into developing a free tool like CapsLock Indicator a failure. So please reevaluate and reflect on what you wrote and I hope you admit your poor behaviour to yourself.

Now, regarding your problem. The screenshot you posted describes a problem already reported in #54 and #58. Also, this issue initally described a completely different problem, so your comment was completely unrelated to this issue in the first place.

If you don't want to wait for me to fix the bug, then maybe consider cloning this repo and fixing the bug yourself. After all, if you say that "as an IT specialist [I am] a failure", you surely must know how to fix the bug you described. CapsLock Indicator does not have a complex codebase whatsoever, so it should be pretty easy to get started.

I hope that you understand my point of view and that you have calmed down a bit.

Have a nice day and best regards!

**Comment by BazzaBoy** [comment]
I have opened the Event Log, but can't find an event pertaining to this app. Sorry, I am not very computer savvy. So, if you give me further instructions, perhaps I can investigate further.

FYI, I downloaded the exe file again today, with the same result.

![image](https://user-images.githubusercontent.com/56054606/94211231-6e602180-ff03-11ea-9978-3b4d5338a3d1.png)

**Comment by jonaskohl** [comment]
Should be fixed in 3.9.0.0. If not, please reopen.
