### ISSUE TITLE
Not changing the colours

### ISSUE THREAD

**Issue by Paultx** [jonaskohl/CapsLockIndicator#56]
I go to Notification settings > Colours and change colours for the border (activated/deactivated) then hit Save & close.
Nothing changes.

My system is Windows 10 Pro 2004 19041.508

**Comment by jonaskohl** [comment]
This is very odd. In my testing, this seems to work (also done on Windows 10 2004 Build 19041.508). Maybe deleting the config file will help (located at `%APPDATA%\Jonas_Kohl\CLIv3-3.8.1.0.exe_Url_wktugtenf2knwk5sfh4zmmpp4fqryy2g\3.8.0.1\user.config`)

**Comment by jonaskohl** [comment]
It's been a while so I assume I can close this issue. If not, please let me know and I'll reopen it.

**Comment by Paultx** [comment]
I'll try your suggestion next Friday.
