### ISSUE TITLE
Wrongly shown symbols and notifications in the notification area

### ISSUE THREAD

**Issue by hjknoh** [jonaskohl/CapsLockIndicator#6]
Dear JonasKohl!
 First of all, the program is excellent, it does what it should.
But after a few month of use (and an update), there is a big mess in the "notification area" (Windows 7 x64 - German). It might be, that my friend (this is not on my pc) has done something wrong, during the installation, but there is no real installation, as I know. How can he get rid of all the wrongly shown symbols and notifications?

Best regards,
Heiner

![jonaskohlcapslockindicator](https://user-images.githubusercontent.com/31110256/35300486-d1d97ab2-0088-11e8-8cda-9f8f6a557371.png)

**Comment by jonaskohl** [comment]
This seems to be a common bug with Windows 7, so there is sadly nothing I can do about it.
