### ISSUE TITLE
Missing tutorial!

### ISSUE THREAD

**Issue by Leunaam** [jonaskohl/CapsLockIndicator#60]
For inexperienced users like me, saying that the .dll file should be moved to the CLI installation directory doesn't make any sense! I don't know what that means! At least one video, one screen recording, nothing! A friend of mine and I wanted to switch to another program that had the same function, and in Italian. but CLI is really nice and well done, please help us, if you want I can give you my discord id so that you can explain to me, see you soon!

P.S. Really nice program, congratulations!

**Comment by jonaskohl** [comment]
I sadly don't have much time to record any tutorials at the moment, but I understand your point very well! I will definitely improve tutorials and instructions like these in the future. In addition to that, I'm planning to add a feature that allows you to automatically install and update language extensions.
