### ISSUE TITLE
Launch with forced user.config

### ISSUE THREAD

**Issue by thierryb67** [jonaskohl/CapsLockIndicator#62]
Hi,

I test currently your software to deploy it in a VDI environnement. 

I found the settings configured are stored into %appdata% profil but in a random folder 
(ex: %Appdata%\Jonas_Kohl\CapslockStatut.exe_Url_eyze5ued4hsgtj1zasrwbuakwrksq55u\3.8.0.1). 
This random settings seems depend from location where the software is launched.

My goal is to set CapsLockIndicator in the startup of all users with all settings set by me before (using a user.config already configured).
Also was it possible :
- to launch a shortcut from exe containing the user.config settings (the best was to use a central user.config file)
- or to fix a folder (standard name which never change) that I can use to copy the user.config file I want by GPO

Thanks for your reply

Best regards

**Comment by jonaskohl** [comment]
This is sadly not possible with the current implementation. CapsLock Indicator uses the default .NET settings system, and the config path changes with each version. This will be addressed in a future version (also, you might want to take a look at #66)

**Comment by thierryb67** [comment]
Hi,

For the moment I found a "workaround" by GPO (but disable the updates)

![image](https://user-images.githubusercontent.com/72496741/102604519-989d3600-4124-11eb-8b30-f2125f470b52.png)

**Comment by jonaskohl** [comment]
The path for settings is now permanent. Please see version 3.9.0.0. I'm closing this now. If your issue has not been solved, please reopen.
