### ISSUE TITLE
Add Icon for Fn Lock

### ISSUE THREAD

**Issue by michischp** [jonaskohl/CapsLockIndicator#63]
Many laptops have a Fn Lock feature available to switch between function key and usually other features on the F1-F12 keys like volume in/decrease, mute, play/pause, in/decrease brightness and others (e.g. on Dell notebooks, it's the Fn+Esc key). Unfortunately, again, Dell has not spent an LED to indicate whether Fn lock is active or inactive.
So, if this can be added as an additional icon, would really be a great enhancement

**Comment by jonaskohl** [comment]
I'm afraid this is not possible, as this is a OEM specific feature which is not standardized accross devices. Often, this feature is even implemented on a hardware level, so there sadly is not much I can do to support Fn lock inside of CapsLock Indicator, sorry.

**Comment by jonaskohl** [comment]
I haven't heard back from you in a while. I'm assuming I can close this issue? If further questions arise, please let me know and I'll reopen this issue.
