### ISSUE TITLE
Imagen "PNG"

### ISSUE THREAD

**Issue by anffna** [jonaskohl/CapsLockIndicator#65]
Hi guys! Very good this app! How about adding support for png images, or character fonts like webdings?

**Comment by jonaskohl** [comment]
I'm afraid I do not quite understand what you are referring to. Could you please elaborate?

**Comment by jonaskohl** [comment]
Has your question been resolved in the meantime?

**Comment by jonaskohl** [comment]
I'm closing this as I did not hear back from you in over 7 months
