### ISSUE TITLE
How to get the name of the parent folder of the configuration file "user.config"?

### ISSUE THREAD

**Issue by mingweme** [jonaskohl/CapsLockIndicator#66]
I really like your software, so I want to use it on another computer, but the parent folder name where the config file is located looks random, how can I get the parent folder name of the config file "user.config"?
My folder name: 
C:\Users\Shann\AppData\Local\Jonas_Kohl\CLIv3-3.8.0.1.exe_Url_poqnwfpptl5utwj4a44jvxohx55fly0l\3.8.0.1\user.config
md5 query result:
md5(poqnwfpptl5utwj4a44jvxohx55fly0l,32) = 6b5843de8bfce66639411bcb03314904
md5(poqnwfpptl5utwj4a44jvxohx55fly0l,16) = 8bfce66639411bcb
Thanks.

**Comment by jonaskohl** [comment]
I'm using the default .NET settings system. This generates the path based on the hash of the application. [This StackOverflow answer](https://stackoverflow.com/a/45112560) might send you in the right direction of determining the settings path.

**Comment by mingweme** [comment]
> I'm using the default .NET settings system. This generates the path based on the hash of the application. [This StackOverflow answer](https://stackoverflow.com/a/45112560) might send you in the right direction of determining the settings path.

**Comment by mingweme** [comment]
> I'm using the default .NET settings system. This generates the path based on the hash of the application. [This StackOverflow answer](https://stackoverflow.com/a/45112560) might send you in the right direction of determining the settings path.

Thanks brother, I have to study the problem.
