### ISSUE TITLE
Dsitribute program with included latest language files

### ISSUE THREAD

**Issue by bovirus** [jonaskohl/CapsLockIndicator#68]
@jonaskohl 

I have a proposal for program distribution.

Instaed to distribute only exe file, I propose to distribute an archive with inside main exe file plus all language subfolders that contains all langauge files available at program release date.

The the user can find already most of time the language file requested without additional download.

**Comment by jonaskohl** [comment]
I'm planning on introducing a system where you can automatically download language extensions directly from CapsLock Indicator itself. Until then, the only way to download translations are from https://cli.jonaskohl.de/!/translations

**Comment by VladWinner** [comment]
@jonaskohl Please update the localization files on this site. Russian lines remain uncorrected (old translation with text that does not fit in UI).

**Comment by jonaskohl** [comment]
The new language files have been uploaded. Please (re)download them at https://cli.jonaskohl.de/!/translations#download-translations.

**Comment by bovirus** [comment]
@jonaskohl

Is it OK now?
