### ISSUE TITLE
Windows Defender Security Center sees Trojan

### ISSUE THREAD

**Issue by DominikJaniec** [jonaskohl/CapsLockIndicator#7]
When downloading 3.4.2.0 version from [home page](http://cli.jonaskohl.de/!/download#latest) the Windows Defender Security Center finds: [`Trojan:Win32/Fuerboos.C!cl`](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Fuerboos.C!cl), but previous version is OK for Windows.

Also, apparently VirusTotal does not see any problem with newest version: https://www.virustotal.com/#/file/09876a9f98dde4ce8e0e96dc057457c7f21db278656fcca715da63ed3ac02e2f/detection

**Comment by tolgabalci** [comment]
I'm seeing the same virus report from the auto update.

CapsLock Indicator prompted me to download a new version to fix a issue with the overlay when the start bar is not on the bottom (which applies to me, I have it on the right, but had not noticed any issues).

After accepting the update, it installed and asked me to restart, which I did and Windows Defender immediately showed a toast message stating that I had a virus (New Caps Lock did not launch). Clicking on the details shows:

![image](https://user-images.githubusercontent.com/2467618/36239872-1426cc72-11db-11e8-8a95-78292558bb53.png)

**Comment by jonaskohl** [comment]
That seems to be a false positive (google "_fuerboos c cl false positive_"). **CapsLock Indicator is, and will always be, free of malware.** Have a look at the source code on here! If you don't trust the precompiled binaries, you can always compile the source code yourself.
