### ISSUE TITLE
Change the scale of CapsLock Indicator

### ISSUE THREAD

**Issue by WhosPix3l** [jonaskohl/CapsLockIndicator#72]
Hello! I really like CapsLock Indicator as my keyboard doesn't have one, haha. Sadly however my main display is 1080p, and on 100% scale so the notification is barely noticeable. I would love to have a slider that I can use to increase the scaling of CapsLock Indicator.

**Comment by vertigo220** [comment]
Did you try increasing the font size?

**Comment by WhosPix3l** [comment]
how does one do that

**Comment by vertigo220** [comment]
Run it, double-click on tray icon, click "Notification settings" button, click button in "Font" section, and change it.

**Comment by WhosPix3l** [comment]
ohh okay, thank you so much!
