### ISSUE TITLE
problem with show/hide icons

### ISSUE THREAD

**Issue by hlopeslima** [jonaskohl/CapsLockIndicator#73]
Hello. Please, i installed your program CapsLockIndicator v3-3.9.1.0.exe. Now i dont want to use it anymore.  The problem is that the "activate/deactivate icon" options (at the task bar configuration) stay there and i can't remove it. How do i remove this options? i tried even the Windows Recovery for yesterday but didn' work

**Comment by jonaskohl** [comment]
I'm afraid I don't quite understand what you are referring to. Please elaborate on this issue (maybe also attach some screenshots if applicable).

**Comment by Yetoo1** [comment]
> Hello. Please, i installed your program CapsLockIndicator v3-3.9.1.0.exe. Now i dont want to use it anymore. The problem is that the "activate/deactivate icon" options (at the task bar configuration) stay there and i can't remove it. How do i remove this options? i tried even the Windows Recovery for yesterday but didn' work

Did you try unchecking "Start on logon"?

**Comment by jonaskohl** [comment]
I haven't heard back from you in quite some time. I will now close this issue
