### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by vertigo220** [jonaskohl/CapsLockIndicator#74]
First, thank you for this. While I actually do have a light on my caps lock key, I still like to see an on-screen notification since I sometimes accidentally hit it and don't notice right away. And this is the only program I've found that does this, so kudos to you for making it. Also, I know you're working on a revamped version, so I doubt any of these requests would make it into the current one and would need to wait for that one.

- Add option to hide notification icon (for the program itself). If needed, it can be accessed by running it again, or you could even add an option to open the settings when CapsLock is pressed four time in quick succession (wouldn't want to do two for obvious reasons, and three would then leave it on, so four seems like the best option) or by double-clicking the overlay.
- Add more zones to allow more precise placement of the overlay. I don't want it dead-center, but bottom-center is too low. I'd prefer if it were about 1/4-1/6 up from the bottom. Or it could just use x,y coordinates or have a small box inside a big box that could be moved around freely to choose where to show it (it would have to have some sort of snapping, so it wouldn't be off-centered, etc)
- Allow the messages to be customized. For example, IMO using a single character or icon is much better. It's less cluttered, easily to very quickly interpret (vs having to read four words), and works for many more languages. So I'd like to be able to set it to something like A/a or A/₳ (tho one with a diagonal line might be better) or a green/red A or even images, maybe one with a locked green lock with the word CAPS in it and one with an unlocked red lock with CAPS in it. Lots of ways to go with it, but I think any would be better than a full, albeit short, sentence that "Caps lock is on/off."

**Comment by vertigo220** [comment]
Another one:

- At least optionally (and ideally by default), save settings in same folder as exe, to make it truly portable. It currently isn't, since it modifies the %appdata% dir, which, aside from possible problems that may cause when a user expects it to be truly portable (i.e. leave no trace), makes it harder to carry settings over. If they're stored with the exe, then both files can simply be copied to another computer very easily.

**Comment by vertigo220** [comment]
In addition to the above suggested changes to the indicator appearance, the ability to adjust the border thickness would help, too. I find just the green and red is easier to quickly use to tell the state, but it's so think it's often difficult to see well enough for it to be useful. I'd also like the option to have a small icon stay on the screen as long as caps lock is on, with its own location and size setting, so instead of having it in the middle(ish) of the screen like the main indicator, I could have a smaller one off in the corner, so I can see at a glance if it's on.

**Comment by jonaskohl** [comment]
I will address your ideas in order below.
1. I don't think this would be a great option in terms of user experience, as it would be easy to accidentally trigger the settings. For now, I'll stick to the usual method of using a tray icon, as most users are very familiar with that concept.
2. I'm looking into this and already started developing a solution, however, it will take some time until that feature can be shipped.
3. This has been added in version 3.10.0.0 under advanced settings.
4. This has also been added in version 3.10.0.0

I hope this addresses your concerns. Please let me know if I can close this issue!

**Comment by vertigo220** [comment]
1. Even if you don't add the "shortcut" to open settings, what about just having an option to hide the icon and open settings through the start menu. Again, it would be an option, so people that don't know how to use the start menu could leave the icon there. Though it would require an exit button in the main windowAlso, I should mention that the icon is extremely difficult to see against a dark-themed taskbar.
2. Cool, looking forward to it. At least with 3 & 4 this one isn't quite so important, since it's easier to see now and I'm able to tell the state much quicker.
3. Thanks! I'd still prefer being able to use images, but this is certainly much better.
4. Again, thanks. What are your thoughts about an optional continuous icon as mentioned, for when caps/num/scroll are active?

**Comment by MalvadoChefe** [comment]
I was searching the hide notification icon suggestion! Jonas you're program is perfect, thank you! :)
