### ISSUE TITLE
Task Bar Icons

### ISSUE THREAD

**Issue by DDBivens** [jonaskohl/CapsLockIndicator#78]
CapsLockIndicator task bar icons are static. 
-
It appears my CapsLockIndicator task bar icons are static. They don't change when the Caps and Num locks status actually changes. I would ask that they use the same color settings that are configured for the Notifications settings and do something like "c" "C" and "n" "7"  to show the change in the Caps key and Num Lock key status change.
Also double clicking the Task Bar status icon icon could change the status of the cap/num lock keys instead of showing the caps locks window.
Just some thoughts. I hope they help.

**Comment by Yetoo1** [comment]
@DDBivens What may have happened is the program crashed and didn't close after the .net exception prompt was closed. Try killing CLIv3-<insert version number> in task manager and then reopening the executable. I recommend to download the latest version because, although the .NET exception still occurs, pressing continue in the prompt won't cause the icons to hang.

**Comment by DDBivens** [comment]
Thanks for the reply.I wasn't having a net exception error.I put in a couple of recommendations about the appearance of the task bar icons.
I hope the suggestions are helpful.Again, thanks for reaching out.
Darrell

    On Saturday, February 27, 2021, 04:00:16 PM EST, Yetoo1 <notifications@github.com> wrote:  
 
 


@DDBivens What may have happened is the program crashed and didn't close after the .net exception prompt was closed. Try killing CLIv3- in task manager and then reopening the executable. I recommend to download the latest version because, although the .NET exception still occurs, pressing continue in the prompt won't cause the icons to hang.

**Comment by jonaskohl** [comment]
This seems to be an issue with an old version which seems to be fixed in subsequent releases. I will assume this issue is resolved.
