### ISSUE TITLE
[BUG] On every start, wipes "usercfg" clean.

### ISSUE THREAD

**Issue by DUOLabs333** [jonaskohl/CapsLockIndicator#79]
I use the most recent version, and I'm using it in portable mode with "usercfg". Every time I start it, it starts with the same welcome screen and wipe my settings clean.

**Comment by jonaskohl** [comment]
This is a bug, which I have already found and fixed. The fix will be released with the next version.

**Comment by DUOLabs333** [comment]
@jonaskohl Is it in the git repo so I could build it from source?

**Comment by jonaskohl** [comment]
I just pushed the fix to the repo. You should now be able to build from source. A full release including this fix will be available very soon.

**Comment by DUOLabs333** [comment]
@jonaskohl Thanks, works perfectly now.
