### ISSUE TITLE
Question: Can you script this for a terminal server environment? 

### ISSUE THREAD

**Issue by neckermann** [jonaskohl/CapsLockIndicator#8]
Looking to see if I can get this to work with cmd line arguments for a script that runs for each user and have the settings be the same?

**Comment by jonaskohl** [comment]
This sounds like a good idea. I'll implement this at some point!

**Comment by neckermann** [comment]
I also notice the user.config gets put in to appdata\local and maybe a good idea to move it to roaming in case the users have roaming profiles?

**Comment by neckermann** [comment]
Here is what I ended up doing.

Rename the exe to my liking
Made the settings to my liking and pulled the user.config from appdata
Put the exe, .config and the following script in a folder the user has access to.
mkdir "%userprofile%\AppData\Local\Jonas_Kohl\CapsLockIndicator.exe_Url_fnd2mzy3sjzqwbnekh4iepmd1f1hr34c\1.0.0.0"
copy "C:\CapsLockIndicator\user.config" "%userprofile%\AppData\Local\Jonas_Kohl\CapsLockIndicator.exe_Url_fnd2mzy3sjzqwbnekh4iepmd1f1hr34c\1.0.0.0\"
start "" "C:\CapsLockIndicator\CapsLockIndicator.exe"

In the users log on script.
REM On Terminal Server TS01 and TS02 run caps lock notification app
if exist C:\CapsLockIndicator ("C:\CapsLockIndicator\CapsLockIndicator.cmd")

**Comment by jonaskohl** [comment]
Command line arguments have been implemented in version 3.5.0.0. Visit [http://cli.jonaskohl.de/!/commandline](http://cli.jonaskohl.de/!/commandline).
