### ISSUE TITLE
Windows 8.1 / 3.10.0.0 It does not run as a normal user

### ISSUE THREAD

**Issue by PeterAdam** [jonaskohl/CapsLockIndicator#80]
Today a friend called me that after a Windows Update last week, the taskbar icons gone again. It does not start, neither double clicking, nor at login.

Running it as administrator makes it running and working, but a single exception after the first press of Caps Lock.

**Comment by jonaskohl** [comment]
I can't reproduce this bug. Could you please provide more information about the bug and the environment?

**Comment by jonaskohl** [comment]
I havent heard back from you in a long time. As I lack essential information about this issue, I will now close this

**Comment by PeterAdam** [comment]
Sorry for the late answer, a later build solved the problem, now works. It should be purchased by the laptop makers who omit the LED lights from the keyboard :)
