### ISSUE TITLE
Windows Defender flagging it as Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by TsukiZero** [jonaskohl/CapsLockIndicator#82]
Didn't happen before.

**Comment by jonaskohl** [comment]
This is a false positive. CapsLock Indicator is not a trojan or any other kind of malware. If you don't trust the pre-compiled binaries, you can always compile from source.

**Comment by ilbalta** [comment]
Windows actually stopped the process and deleted the file on my end.
As @TsukiZero said, this never happened before to me as well. 
Would it be possible to restore the previous behavior? I'm unsure what might have triggered this false positive but I cannot add exceptions to my company computer so for the time being I am sadly unable to use the latest version of the program :(

**Comment by ilbalta** [comment]
It seems a recent windows defender definition update solved the issue, I re-downloaded the latest version and now Defender is chill!

**Comment by jonaskohl** [comment]
As I haven't heard anything back for a while, I assume this issue has been solved and can be closed.
