### ISSUE TITLE
Tray icon issues

### ISSUE THREAD

**Issue by vertigo220** [jonaskohl/CapsLockIndicator#83]
1) Icon is difficult to see when using dark Windows theme.
2) Launching app from icon causes icon to briefly disappear and reappear, and even though it appears to happen _after_ the second click, it _acts_ like it's happening after the _first_ click, because every time I double-click on it, MS PowerToys, which is the tray icon to the right of this one, gets opened.

**Comment by jonaskohl** [comment]
1. Have you tried using the dark theme? (Found under advanced settings, set `darkTheme` to `true`)
2. Strange, I have not come across this behaviour myself. I'll look into it.

**Comment by vertigo220** [comment]
1. I don't see a darkTheme, only darkMode. And not only does that not change the tray icon, but it makes the UI unreadable:

![2021-04-05 23_37_05-CapsLock Indicator](https://user-images.githubusercontent.com/12024557/113655469-e1431580-9667-11eb-8470-716878443ba8.png)

2. I figured out that CLI opens on mouse-down of the second click, and when it opens the icon disappears for a split-second, which is just long enough for the icons to shift, resulting in (in my case) the PowerToys icon to be where the cursor is, and that just happens to be a single-click to launch icon and is apparently triggered by the mouse-up of the click. Very strange, and not likely to be a common issue, but an issue nonetheless. Hope that helps.

**Comment by jonaskohl** [comment]
1. Sorry, my bad. The option is indeed named `darkMode`. And I'll look into the unreadable UI. I noticed that on my side as well.
2. Okay, now I can reproduce the bug. I'll look into this later today

**Comment by jonaskohl** [comment]
Does this issue still occur in the latest version?

**Comment by vertigo220** [comment]
The first issue, that the icon is difficult to see, still exists. The second issue still partially exists, but is at least no longer a problem. The icon still disappears and reappears quickly while being double-clicked, and when this happens all the other icons shift over briefly then back, so it looks weird, but at least it doesn't cause the neighboring icon to be clicked anymore.

**Comment by snowleopard-1** [comment]
I recently bought an ASUS TUF.

I get the notification when num lock goes on and off. But shoudldn't the icon also switch? I just see an "N" whenther num lock is on or off. I would also like the icon to be in the task bar itself and not among the "extra" icons accessible by the up arrow.

I don't use Windows so much and am new to this so I may have misunderstood.
Thank you for keep up open software.

**Comment by jonaskohl** [comment]
@snowleopard-1 To keep things organized, issue threads are for one issue only. Please [open a new issue](https://github.com/jonaskohl/CapsLockIndicator/issues/new) and report your problem again.
