### ISSUE TITLE
Update file extension missing.

### ISSUE THREAD

**Issue by Padre2** [jonaskohl/CapsLockIndicator#84]
On Window 7, the update file for versions 3.11.1.0 and 3.11.1.1 download without the _.exe_ extension.
Adding it resolves the problem, but why is it happening?

**Comment by jonaskohl** [comment]
This was a server-side bug and has been fixed now! Please let me know if your issue has been resolved, so I can close this issue if that is the case.

**Comment by Padre2** [comment]
File now downloads with the extension.Vielen Dank.
