### ISSUE TITLE
Translation issue - pt-BR

### ISSUE THREAD

**Issue by JOAOPUSERNET** [jonaskohl/CapsLockIndicator#86]
In this latest version 3.11.1.0 and setting to pt-BR, after start on logon always come back to English(United kingdom)
In pt-BR, the letters overlap
Thanks for your great job.
![1](https://user-images.githubusercontent.com/82158339/114034644-bff34c80-9854-11eb-9eb2-8b2d39a78a53.jpg)
![2](https://user-images.githubusercontent.com/82158339/114034682-c97cb480-9854-11eb-90d7-1ffb5aaa0885.JPG)

**Comment by JOAOPUSERNET** [comment]
I tested all langages and this issue happens with the translations Portuguese (Brazil) [pt-BR], Turkish [tr-TR], Chinese Simplified [zh-CN] and Portuguese (Portugal) [pt-PT].
The other languages is ok.

**Comment by oleg-sgh** [comment]
1. After each restart of the program, the Russian language is discharged into English.

2. After each restart of the program, edits are reset in the usercfg file, on default settings.

Version 3.11.1.0
Windows 7x64.

**Comment by jonaskohl** [comment]
This is an issue which will hopefully be fixed by #89

**Comment by jonaskohl** [comment]
Should be fixed with [Version 3.12.0.0](https://cli.jonaskohl.de/!/download)

**Comment by JOAOPUSERNET** [comment]
Great job. Version 3.12.0.0 works correctly.

**Comment by jonaskohl** [comment]
That's great to hear! I'm closing this now as the issue seems to be solved
