### ISSUE TITLE
Exception from time to time

### ISSUE THREAD

**Issue by RamonCar66** [jonaskohl/CapsLockIndicator#87]
Hello,
From time to time, when I press CapsLock key, I receive a .Net exception. I press continue, and the programs continue to work.
Version is 3.8. I've tried to upgrade to latest version 3.11, but then I recieve exception when trying to setup my personal colors.
Therefore, I've reverted to v 3.8

![image](https://user-images.githubusercontent.com/65061885/114266599-7131e800-99f7-11eb-87e7-01f42191ec35.png)

    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3630.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3680.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Thansk a lot !

**Comment by jonaskohl** [comment]
Please manually update to the latest version! Version 3.8 is not supported anymore.

**Comment by RamonCar66** [comment]
Thanks Jonas, I've updated.
