### ISSUE TITLE
Exception when trying to change notification color.

### ISSUE THREAD

**Issue by RamonCar66** [jonaskohl/CapsLockIndicator#88]
Hello,
There is an exception when trying to change the color of the notifications.

![image](https://user-images.githubusercontent.com/65061885/114269265-5adf5880-9a06-11eb-97ef-12fdaf6e7d09.png)

Thanks a lot for your help

**Comment by jonaskohl** [comment]
This may be because of the partial dark mode implementation in native dialogs. I will roll back this change. What version of Windows 10 are you using?

**Comment by jonaskohl** [comment]
This should be fixed in version 3.12.0.0

**Comment by jonaskohl** [comment]
I am closing this now as I haven't heard back from you in over 30 days.
