### ISSUE TITLE
Allow customisation of the tray icon's border colour 

### ISSUE THREAD

**Issue by adrmzz** [jonaskohl/CapsLockIndicator#9]
The icons on the tray have red and green colours. Contrarily to notifications, which can be customised through the button "Notification settings", tray icons's border colour cannot be customised. Furthermore, since red might be associated with "alarm", it might be induce error.

**Comment by jonaskohl** [comment]
I thought of this as well and I'd like to add this. However I first need to figure out how to generate these icons on the fly without a huge performance impact.

**Comment by jonaskohl** [comment]
I have now added a feature to [load custom ICO files](http://cli.jonaskohl.de/!/icons) in [Version 3.6.0.0](http://cli.jonaskohl.de/!/details/3.6.0.0). Not quite what you requested, but it allows for even more customisation.
