### ISSUE TITLE
"Right click on sys tray icon" -> "Exit" only ends process if GUI has been displayed

### ISSUE THREAD

**Issue by InsanityOnABun** [jonaskohl/CapsLockIndicator#91]
If the GUI has not been displayed, for example if it launched at startup with "start on logon" and "hide on start up" both checked, and you don't double click the icon to open the GUI before right clicking the icon and exiting, the icons disappear but the actual process persists in Task Manager. At that point you have to kill the process manually to relaunch it.

**Comment by jonaskohl** [comment]
Fixed in version [3.13.3.0](https://cli.jonaskohl.de/!/details/3.13.3.0)
