### ISSUE TITLE
Message saying that Windows version is unsupported

### ISSUE THREAD

**Issue by EverEve** [jonaskohl/CapsLockIndicator#94]
Hello,

Today I've upgraded to version 3.13.5.0 and received this very message:

![immagine](https://user-images.githubusercontent.com/6781183/134175080-24ae0219-c693-416b-b2a2-7d8d55405ebb.png)

Version 1809 LTSC will be receiving  support for 10 years. 
When do you plan to end support for this version?

Thanks.

**Comment by quicksand77** [comment]
![image](https://user-images.githubusercontent.com/10732820/134931548-4c35d555-d740-4388-a1df-c3fed1e65c07.png)

Getting a similar issue with windows 10 version 1909

**Comment by EverEve** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/10732820/134931548-4c35d555-d740-4388-a1df-c3fed1e65c07.png)
> 
> Getting a similar issue with windows 10 version 1909

Ok, but while actually Microsoft stopped supporting build 1909 in May 2021, build 1809 for enterprises will receive support until 2029

https://docs.microsoft.com/en-us/lifecycle/products/windows-10-ltsc-2019

**Comment by jonaskohl** [comment]
All end-of-life data stems from [https://endoflife.date/windows](endoflife.date). Over there, it says Windows 10 1803 (all versions) are unsupported. I suspect this is an error in their data. There is sadly nothing I can do as manually overwriting the data and keeping it up to date would involve much more work than I can invest at the moment.

To avoid this banner, you can disable the end-of-life check completely by opening up the advanced settings and settings `supressEOLMessage` to `True`.

**Comment by EverEve** [comment]
Sorry, I was referring to the fact that you will plan to end support for these OS versions.
