### ISSUE TITLE
Persistent Notification Option

### ISSUE THREAD

**Issue by burkybang** [jonaskohl/CapsLockIndicator#98]
I think it would be very useful to have 2 options for each notification type that would allow for the notification to be persistent.

### Use Case
It's isn't normal for me to have caps lock on for a long time, so I would like to see the "Caps lock is on" notification for the entire time that my caps lock is enabled. Yes, I can use the icon for this, but on my 4K monitor set at 100%, it's not as convenient for me to glance over at my task tray to find the tiny icon.

### Mockup
![image](https://user-images.githubusercontent.com/927886/137937610-4da2e183-f782-4a57-9e2c-7edd113d946e.png)

**Comment by jonaskohl** [comment]
I will consider this, although this has a low priority at the moment. Any PRs are welcome, though
